### ISSUE TITLE
Buffer size

### ISSUE THREAD

**Issue by xin-jin** [kiwanami/emacs-window-manager#79]
Is there any way to customize buffer sizes in init.el? For instance, I find the dired buffer (under code perspective) too wide by default and wish to make it thinner.

Thanks!

**Comment by xin-jin** [comment]
OK, I've found the way. Put the following into init.el:

```
(setq e2wm:c-code-recipe
      '(| (:left-max-size 20)
          (- (:upper-size-ratio 0.6)
             files history)
          (- (:lower-max-size 150)
             (| (:right-max-size 40)
                main imenu)
             sub)))
```

change `left-max-size`.

**Comment by kiwanami** [comment]
Hi @xin-jin 
Yes, your code is right!

I'm sorry for lack of documentation.
You can see some document for the configuration for window layout at the comments in `window-layout.el`:
https://github.com/kiwanami/emacs-window-layout/blob/master/window-layout.el#L72

If you need more support, please tell me.

**Comment by xin-jin** [comment]
Thanks! I am just wondering if there is a way to make, say, python-code-recipe  and use it easily? When coding in c, eshell comes handy, but the two my most used languages (python and ocaml) have their own REPLs. So it would be better to let *Python3* or *utop* (ocaml's REPL) be in the `sub` area.

**Comment by xin-jin** [comment]
I am sorry. I found out that actually `utop` does work just like eshell. But python does not: when open python interpreter, it does not show up in the `sub` area.
