### ISSUE TITLE
Layout bug when Emacs built with GTK3

### ISSUE THREAD

**Issue by johalun** [kiwanami/emacs-window-manager#88]
Hi

When using Emacs built with GTK3 e2wm split windows vertical scrollbar are in the wrong horizontal positions. 
Also, the e2wm menu does not display at all (not imenu, the x11 app menu (file edit options etc)).

**Comment by johalun** [comment]
Also see
#https://github.com/kiwanami/emacs-window-layout/issues/12

This only appears on HiDPI display with gnome scaling factor = 2 and Emacs built with GTK3.

**Comment by johalun** [comment]
Seem to be emacs/gtk3 scrollbar problem.

**Comment by kiwanami** [comment]
Hi @johalun 
Thank you for your information about a trouble of combination with HiDPI and GTK3.
It's useful for the people who use large HiDPI displays.
